# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wait...are you not?
email: ayn@areyounot.com
description: > # this means to ignore newlines until "baseurl:"
  Wait...are you not?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://areyounot.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  andreistephens

# Build settings
markdown: kramdown
